name = "github-webhook-proxy"
type = "javascript"
account_id = ""
zone_id = ""
workers_dev = true

[build]
command = "npm install && npm run build --resolveJsonModule"
[build.upload]
format = "service-worker"
